[pytest]
testpaths = tests
pythonpath = .
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
source = app,evaluation
omit =
    app/rag/*
    app/main.py
    */venv/*

[coverage:report]
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
fail_under = 50
show_missing = True
